/**
* Example Code generated by Beijing Volcanoengine Technology.
*/
package com.volcengine.bigmodel.examples;

import com.volcengine.ApiClient;
import com.volcengine.ApiException;
import com.volcengine.bigmodel.AVDigestApi;
import com.volcengine.bigmodel.model.QuerySongRequest;
import com.volcengine.bigmodel.model.QuerySongResponse;
import com.volcengine.sign.Credentials;


public class TestQuerySong {
    public static void main(String[] args) throws Exception {
        String ak = "AKLTZDA5OGZjMzEwMTI5NDkwMWIxNjQyZDg4OWQ3YjI3YTY";
        String sk = "TmpKaFltVTROVGc1TVdOak5HVXhaRGxsTldSa1kyUmlZV0l6WW1ZMVlXTQ==";
        String region = "cn-beijing";

        ApiClient apiClient = new ApiClient()
                .setCredentials(Credentials.getCredentials(ak, sk))
                .setRegion(region);

        AVDigestApi api = new AVDigestApi(apiClient);

        QuerySongRequest querySongRequest = new QuerySongRequest();
        querySongRequest.setTaskID("202505354919787870027777");

        try {
            QuerySongResponse response = api.querySong(querySongRequest);
            System.out.println(response);
        } catch (ApiException e) {
            System.out.println(e.getResponseBody());
        }
    }
}