/**
* Example Code generated by Beijing Volcanoengine Technology.
*/
package com.volcengine.bigmodel.examples;

import com.volcengine.ApiClient;
import com.volcengine.ApiException;
import com.volcengine.bigmodel.AVDigestApi;
import com.volcengine.bigmodel.model.GenSongForTimeRequest;
import com.volcengine.bigmodel.model.GenSongForTimeResponse;
import com.volcengine.sign.Credentials;


public class TestGenSongForTime {
    public static void main(String[] args) throws Exception {
        String ak = "AKLTZDA5OGZjMzEwMTI5NDkwMWIxNjQyZDg4OWQ3YjI3YTY";
        String sk = "TmpKaFltVTROVGc1TVdOak5HVXhaRGxsTldSa1kyUmlZV0l6WW1ZMVlXTQ==";
        String region = "cn-beijing";

        ApiClient apiClient = new ApiClient()
                .setCredentials(Credentials.getCredentials(ak, sk))
                .setRegion(region);

        AVDigestApi api = new AVDigestApi(apiClient);

        GenSongForTimeRequest genSongForTimeRequest = new GenSongForTimeRequest();
        genSongForTimeRequest.setPrompt("写一首关于烟花的歌");
        genSongForTimeRequest.setGender("Male");
        genSongForTimeRequest.setGenre("Pop");
        genSongForTimeRequest.setMood("Happy");
        
        try {
            GenSongForTimeResponse response = api.genSongForTime(genSongForTimeRequest);
            System.out.println(response);
        } catch (ApiException e) {
            System.out.println(e.getResponseBody());
        }
    }
}