/*
 * imagination
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.bigmodel.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.validation.Valid;
import java.util.Objects;
/**
 * FailureReason
 */



public class FailureReason {
  @SerializedName("Code")
  private Integer code = null;

  @SerializedName("Msg")
  private String msg = null;

  public FailureReason code(Integer code) {
    this.code = code;
    return this;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

   /**
   * Get code
   * @return code
  **/
  @Valid
  @Schema(description = "")
  public Integer getCode() {
    return code;
  }


  public FailureReason msg(String msg) {
    this.msg = msg;
    return this;
  }

   /**
   * Get msg
   * @return msg
  **/
  @Schema(description = "")
  public String getMsg() {
    return msg;
  }

  public void setMsg(String msg) {
    this.msg = msg;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    FailureReason that = (FailureReason) o;
    return Objects.equals(code, that.code) && Objects.equals(msg, that.msg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, msg);
  }

  @Override
  public String toString() {
    return "FailureReason{" +
            "code=" + code +
            ", msg='" + msg + '\'' +
            '}';
  }
}
