/*
 * imagination
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.bigmodel.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * GenSongForTimeResponse
 */


public class GenSongForTimeResponse extends com.volcengine.model.AbstractResponse {
  @SerializedName("TaskID")
  private String taskID = null;

  @SerializedName("PredictedWaitTime")
  private Long predictedWaitTime = null;

  public GenSongForTimeResponse taskID(String taskID) {
    this.taskID = taskID;
    return this;
  }

   /**
   * Get taskID
   * @return taskID
  **/
  @Schema(description = "")
  public String getTaskID() {
    return taskID;
  }

  public void setTaskID(String taskID) {
    this.taskID = taskID;
  }

   /**
   * Get predictedWaitTime
   * @return predictedWaitTime
  **/
  @Schema(description = "")
  public Long getPredictedWaitTime() {
    return predictedWaitTime;
  }

  public void setPredictedWaitTime(Long predictedWaitTime) {
    this.predictedWaitTime = predictedWaitTime;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    GenSongForTimeResponse that = (GenSongForTimeResponse) o;
    return Objects.equals(taskID, that.taskID) && Objects.equals(predictedWaitTime, that.predictedWaitTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskID, predictedWaitTime);
  }

  @Override
  public String toString() {
    return "GenSongForTimeResponse{" +
            "taskID='" + taskID + '\'' +
            ", predictedWaitTime=" + predictedWaitTime +
            '}';
  }

}
