/*
 * imagination
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.bigmodel.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.validation.constraints.NotNull;
import java.util.Objects;
/**
 * GenSongForTimeRequest
 */



public class GenSongForTimeRequest {
  @SerializedName("Prompt")
  private String prompt = null;

  @SerializedName("Genre")
  private String genre = null;

  @SerializedName("Mood")
  private String mood = null;

  @SerializedName("Gender")
  private String gender = null;

  @SerializedName("Timbre")
  private String timbre = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("Duration")
  private Integer duration = null;

  @SerializedName("CallbackURL")
  private String callbackURL = null;

  @SerializedName("SkipCopyCheck")
  private Boolean skipCopyCheck = null;

  @SerializedName("TosBucket")
  private Boolean tosBucket = null;

  /**
   * Get prompt
   * @return prompt
   **/
  @NotNull
  @Schema(required = true, description = "")
  public String getPrompt() {
    return prompt;
  }

  public void setPrompt(String prompt) {
    this.prompt = prompt;
  }

  /**
   * Get gender
   * @return gender
   **/
  @NotNull
  @Schema(required = true, description = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  /**
   * Get mood
   * @return mood
   **/
  @NotNull
  @Schema(required = true, description = "")
  public String getMood() {
    return mood;
  }

  public void setMood(String mood) {
    this.mood = mood;
  }

  /**
   * Get genre
   * @return genre
   **/
  @NotNull
  @Schema(required = true, description = "")
  public String getGenre() {
    return genre;
  }

  public void setGenre(String genre) {
    this.genre = genre;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    GenSongForTimeRequest that = (GenSongForTimeRequest) o;
    return Objects.equals(prompt, that.prompt) && Objects.equals(genre, that.genre) && Objects.equals(mood, that.mood) && Objects.equals(gender, that.gender) && Objects.equals(timbre, that.timbre) && Objects.equals(name, that.name) && Objects.equals(duration, that.duration) && Objects.equals(callbackURL, that.callbackURL) && Objects.equals(skipCopyCheck, that.skipCopyCheck) && Objects.equals(tosBucket, that.tosBucket);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prompt, genre, mood, gender, timbre, name, duration, callbackURL, skipCopyCheck, tosBucket);
  }

  @Override
  public String toString() {
    return "GenSongForTimeRequest{" +
            "prompt='" + prompt + '\'' +
            ", genre='" + genre + '\'' +
            ", mood='" + mood + '\'' +
            ", gender='" + gender + '\'' +
            ", timbre='" + timbre + '\'' +
            ", name='" + name + '\'' +
            ", duration=" + duration +
            ", callbackURL='" + callbackURL + '\'' +
            ", skipCopyCheck=" + skipCopyCheck +
            ", tosBucket=" + tosBucket +
            '}';
  }

}
