/*
 * imagination
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.bigmodel.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * QuerySongRequest
 */



public class QuerySongRequest {
  @SerializedName("TaskID")
  private String taskID = null;

  /**
   * Get taskID
   * @return taskID
   **/
  @NotNull
  @Schema(required = true, description = "")
  public String getTaskID() {
    return taskID;
  }

  public void setTaskID(String taskID) {
    this.taskID = taskID;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    QuerySongRequest that = (QuerySongRequest) o;
    return Objects.equals(taskID, that.taskID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskID);
  }

  @Override
  public String toString() {
    return "QuerySongRequest{" +
            "taskID='" + taskID + '\'' +
            '}';
  }
}
