/*
 * imagination
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.bigmodel.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * GenSongV4Response
 */


public class QuerySongResponse extends com.volcengine.model.AbstractResponse {
  @SerializedName("TaskID")
  private String taskID = null;

  @SerializedName("Status")
  private Integer status = null;

  @SerializedName("Progress")
  private Integer progress = null;

  @SerializedName("FailureReason")
  private FailureReason failureReason = null;

  @SerializedName("SongDetail")
  private SongDetail songDetail = null;

  public QuerySongResponse taskID(String taskID) {
    this.taskID = taskID;
    return this;
  }

   /**
   * Get taskID
   * @return taskID
  **/
  @Schema(description = "")
  public String getTaskID() {
    return taskID;
  }

  public void setTaskID(String taskID) {
    this.taskID = taskID;
  }

  public QuerySongResponse status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public QuerySongResponse progress(Integer progress) {
    this.progress = progress;
    return this;
  }

   /**
   * Get progress
   * @return progress
  **/
  @Schema(description = "")
  public Integer getProgress() {
    return progress;
  }

  public void setProgress(Integer progress) {
    this.progress = progress;
  }

  public QuerySongResponse failureReason(FailureReason failureReason) {
    this.failureReason = failureReason;
    return this;
  }

   /**
   * Get failureReason
   * @return failureReason
  **/
  @Schema(description = "")
  public FailureReason getFailureReason() {
    return failureReason;
  }

  public void setFailureReason(FailureReason failureReason) {
    this.failureReason = failureReason;
  }

  public QuerySongResponse songDetail(SongDetail songDetail) {
    this.songDetail = songDetail;
    return this;
  }

   /**
   * Get songDetail
   * @return songDetail
  **/
  @Schema(description = "")
  public SongDetail getSongDetail() {
    return songDetail;
  }

  public void setSongDetail(SongDetail songDetail) {
    this.songDetail = songDetail;
  }

  public boolean isSuccess() {
    return this.status == 200;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    QuerySongResponse that = (QuerySongResponse) o;
    return Objects.equals(taskID, that.taskID) && Objects.equals(status, that.status) && Objects.equals(progress, that.progress) && Objects.equals(failureReason, that.failureReason) && Objects.equals(songDetail, that.songDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskID, status, progress, failureReason, songDetail);
  }

  @Override
  public String toString() {
    return "QuerySongResponse{" +
            "taskID='" + taskID + '\'' +
            ", status=" + status +
            ", progress=" + progress +
            ", failureReason=" + failureReason +
            ", songDetail=" + songDetail +
            '}';
  }
}
