/*
 * imagination
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.bigmodel.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.validation.Valid;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * SongDetail
 */



public class SongDetail {
  @SerializedName("AudioUrl")
  private String audioUrl = null;

  @SerializedName("Captions")
  private String captions = null;

  @SerializedName("Lyrics")
  private String lyrics = null;

  @SerializedName("Duration")
  private BigDecimal duration = null;

  @SerializedName("Genre")
  private String genre = null;

  @SerializedName("Mood")
  private String mood = null;

  @SerializedName("Gender")
  private String gender = null;

  @SerializedName("TosPath")
  private String tosPath = null;

  @SerializedName("CallbackURL")
  private String callbackURL = null;

  @SerializedName("Timbre")
  private String timbre = null;

  @SerializedName("Prompt")
  private String prompt = null;

  public SongDetail audioUrl(String audioUrl) {
    this.audioUrl = audioUrl;
    return this;
  }

  public void setAudioUrl(String audioUrl) {
    this.audioUrl = audioUrl;
  }

   /**
   * Get audioUrl
   * @return audioUrl
  **/
  @Valid
  @Schema(description = "")
  public String getAudioUrl() {
    return audioUrl;
  }


  public SongDetail captions(String captions) {
    this.captions = captions;
    return this;
  }

   /**
   * Get captions
   * @return captions
  **/
  @Schema(description = "")
  public String getCaptions() {
    return captions;
  }

  public void setCaptions(String captions) {
    this.captions = captions;
  }


  public SongDetail lyrics(String lyrics) {
    this.lyrics = lyrics;
    return this;
  }

   /**
   * Get lyrics
   * @return lyrics
  **/
  @Schema(description = "")
  public String getLyrics() {
    return lyrics;
  }

  public void setLyrics(String lyrics) {
    this.lyrics = lyrics;
  }


  public SongDetail duration(BigDecimal duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @Schema(description = "")
  public BigDecimal getDuration() {
    return duration;
  }

  public void setDuration(BigDecimal duration) {
    this.duration = duration;
  }


  public SongDetail genre(String genre) {
    this.genre = genre;
    return this;
  }

   /**
   * Get genre
   * @return genre
  **/
  @Schema(description = "")
  public String getGenre() {
    return genre;
  }

  public void setGenre(String genre) {
    this.genre = genre;
  }


  public SongDetail mood(String mood) {
    this.mood = mood;
    return this;
  }

   /**
   * Get mood
   * @return mood
  **/
  @Schema(description = "")
  public String getMood() {
    return mood;
  }

  public void setMood(String mood) {
    this.mood = mood;
  }


  public SongDetail gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @Schema(description = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }


  public SongDetail tosPath(String tosPath) {
    this.tosPath = tosPath;
    return this;
  }

   /**
   * Get tosPath
   * @return tosPath
  **/
  @Schema(description = "")
  public String getTosPath() {
    return tosPath;
  }

  public void setTosPath(String tosPath) {
    this.tosPath = tosPath;
  }


  public SongDetail callbackURL(String callbackURL) {
    this.callbackURL = callbackURL;
    return this;
  }

   /**
   * Get callbackURL
   * @return callbackURL
  **/
  @Schema(description = "")
  public String getCallbackURL() {
    return callbackURL;
  }

  public void setCallbackURL(String callbackURL) {
    this.callbackURL = callbackURL;
  }


  public SongDetail timbre(String timbre) {
    this.timbre = timbre;
    return this;
  }

   /**
   * Get timbre
   * @return timbre
  **/
  @Schema(description = "")
  public String getTimbre() {
    return timbre;
  }

  public void setTimbre(String timbre) {
    this.timbre = timbre;
  }


  public SongDetail prompt(String prompt) {
    this.prompt = prompt;
    return this;
  }

   /**
   * Get prompt
   * @return prompt
  **/
  @Schema(description = "")
  public String getPrompt() {
    return prompt;
  }

  public void setPrompt(String prompt) {
    this.prompt = prompt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    SongDetail that = (SongDetail) o;
    return Objects.equals(audioUrl, that.audioUrl) && Objects.equals(captions, that.captions) && Objects.equals(lyrics, that.lyrics) && Objects.equals(duration, that.duration) && Objects.equals(genre, that.genre) && Objects.equals(mood, that.mood) && Objects.equals(gender, that.gender) && Objects.equals(tosPath, that.tosPath) && Objects.equals(callbackURL, that.callbackURL) && Objects.equals(timbre, that.timbre) && Objects.equals(prompt, that.prompt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audioUrl, captions, lyrics, duration, genre, mood, gender, tosPath, callbackURL, timbre, prompt);
  }

  @Override
  public String toString() {
    return "SongDetail{" +
            "audioUrl='" + audioUrl + '\'' +
            ", captions='" + captions + '\'' +
            ", lyrics='" + lyrics + '\'' +
            ", duration=" + duration +
            ", genre='" + genre + '\'' +
            ", mood='" + mood + '\'' +
            ", gender='" + gender + '\'' +
            ", tosPath='" + tosPath + '\'' +
            ", callbackURL='" + callbackURL + '\'' +
            ", timbre='" + timbre + '\'' +
            ", prompt='" + prompt + '\'' +
            '}';
  }
}
